# x or y
string axis
# forward or backward
string direction
# center, left, right, stop
string[] steps
---
# Define the result
bool success
geometry_msgs/Pose2D relative_error
---
# Define a feedback message
# Following guide, Looking for fork, Forking, Blind navigation
string state
string[] remaining_steps