# goal
# x or y
string axis
# forward or backward
string direction
# travel distance
float64 distance
---
# result
bool success
geometry_msgs/Pose2D relative_error
---
# feedback
string state
float64 remaining
geometry_msgs/Pose2D relative_error
